### ISSUE TITLE
Maybe a issues?

### ISSUE THREAD

**Issue by KanaTomokawa** [IMB11/Armorful#19]
![1](https://github.com/IMB11/Armorful/assets/51477358/d4bdc0cb-e9b9-427b-aa5c-e127448b85c2)
![2](https://github.com/IMB11/Armorful/assets/51477358/b7a22b15-0a3d-441d-b0fe-b49c9944e6ca)
The datapack file show to wave8, but there's no wave8 in the codes, it only show to wave7, which suggests that in-game, raids wave8's illagers don't wear armor, at least in my game, maybe I'm just unlucky?

**Comment by IMB11** [comment]
Nice spot, will put a hotfix out :+1:

**Comment by IMB11** [comment]
Actually, an 8th wave is possible, i'll have to put it into the armorChances switch (the extra wave on hard difficulty counts as wave 8) 
![image](https://github.com/IMB11/Armorful/assets/93472213/2d14160a-a414-4d75-8745-2ac9807910a5)

**Comment by IMB11** [comment]
Closed in 3.0.1

**Comment by KanaTomokawa** [comment]
> Actually, an 8th wave is possible, i'll have to put it into the armorChances switch (the extra wave on hard difficulty counts as wave 8) ![image](https://private-user-images.githubusercontent.com/93472213/335607271-2d14160a-a414-4d75-8745-2ac9807910a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjQ5MzAsIm5iZiI6MTcxNzE2NDYzMCwicGF0aCI6Ii85MzQ3MjIxMy8zMzU2MDcyNzEtMmQxNDE2MGEtYTQxNC00ZDc1LTg3NDUtMmFjOTgwNzkxMGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YWNjM2JiY2JlOTQwNjlkNDYyMjkzOGQ4NDZlMDM4MzZlYzE1ODdhZjZjMjkzNjNlNGM1M2FhYjkxNDdhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VEkPqdnT8_ih98jEo3aazYDaiIw38TsRNiMLdGiiWWQ)

Let me ask, the illusioner can wear armor? because it can't spawn natural , and MrSterner's grandvillagers fabric mod  dont have illusioner spawn natural option.
